
[functions.create-mux-upload]
enabled = true
verify_jwt = true
import_map = "./functions/create-mux-upload/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-mux-upload/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-mux-upload/*.html" ]

[functions.mux-webhook-handler]
enabled = true
verify_jwt = true
import_map = "./functions/mux-webhook-handler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mux-webhook-handler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mux-webhook-handler/*.html" ]
